# This file is a template, and might need editing before it works on your project.
# This template uses the java:8 docker image
image: java:8

# Clone the xspec sources and set the Saxon Path
before_script:
  - git clone -b master https://github.com/xspec/xspec.git /tmp/xspec
  - mkdir -p /tmp/xspec/saxon
  - export SAXON_CP=/tmp/xspec/saxon/saxon9he.jar
  - wget -O ${SAXON_CP} http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar
  - chmod +x ${SAXON_CP}

# Run the xspec tests with old saxon version
test:saxon_old:
  stage: test
  variables:
    SAXON_VERSION: "9.6.0-7"
  script:
    - cd test
    - ./run-xspec-tests.sh

# Run the xspec tests with new saxon version
test:saxon_new:
  stage: test
  variables:
    SAXON_VERSION: "9.7.0-14"
  script:
    - cd test
    - ./run-xspec-tests.sh
