language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_script:
  - git clone -b master https://github.com/xspec/xspec.git /tmp/xspec
  # install saxon 9.7.0-14
  - mkdir -p /tmp/xspec/saxon
  - wget -O /tmp/xspec/saxon/saxon9he.jar http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/9.7.0-14/Saxon-HE-9.7.0-14.jar
  - chmod +x /tmp/xspec/saxon/saxon9he.jar
  - export SAXON_CP=/tmp/xspec/saxon/saxon9he.jar
script:
  - cd test
  - ./run-xspec-tests.sh
