language: java
jdk:
  - oraclejdk7
  - oraclejdk8
env:
  matrix:
    - SAXON_VERSION=9.7.0-14
    - SAXON_VERSION=9.6.0-7
before_script:
  # install saxon 9.7.0-14
  - git clone -b v0.5.0 https://github.com/xspec/xspec.git /tmp/xspec
  - mkdir -p /tmp/xspec/saxon
  - export SAXON_CP=/tmp/xspec/saxon/saxon9he.jar
  - wget -O ${SAXON_CP} http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar
  - chmod +x ${SAXON_CP}
script:
  - cd test
  - ./run-xspec-tests.sh
